### ISSUE TITLE
Sync version numbers

### ISSUE THREAD

**Issue by memark** [gunar/shellcheck#24]
Thank you for providing this excellent tool via npm!

It would be really helpful if the version numbers were in sync thought. Right now I download `shellcheck@0.4.4` from npm, which actually gives me
```
ShellCheck - shell script analysis tool
version: 0.7.1
```

**Comment by gunar** [comment]
Hi @memark,

Thanks mate! Your words are appreciated.

As for your suggestion, I don't see how it'd work. There are two problems:

1. The downloader code might need to change
   Say I bump the current version to `0.7.1` right now, which would mean it's in sync with the latest shellcheck version. Then let's say a bug comes up, how would I publish the bug-fixed version, given that the tag `0.7.1` is already on npm?
2. The current script always downloads the latest version of shellcheck
    This is doable. I actually wouldn't be opposed to hard-coding version to keep things more stable.

I'm going to close this mainly because of (1). Happy to reopen it if there's something I'm missing and a proposal comes along that solves the problem.

Thanks again for your kind words and for your suggestion.

Cheers,
Gunar

**Comment by memark** [comment]
Oh, now I see! (I think.)

This npm package always downloads and installs the latest version of shellcheck, right? So I can use version 0.4.4 to install future versions of shellcheck as well? Then it's no longer a problem!

Maybe we can mention this fact a bit more clearly in the docs?

**Comment by gunar** [comment]
Done! Thank you for the feedback.
