### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by gunar** [gunar/shellcheck#8]

**Comment by gunar** [comment]
No upvotes in a year. Closing this for now. Anyone welcome to reopen it.

**Comment by joelvaneenwyk** [comment]
Didn't realize a close was going to happen without an upvote. Upvoted! I've actually been waiting on this one. @gunar , do you suspect this to be a considerable amount of work?

**Comment by gunar** [comment]
Thanks for voting! Off the top of my head, here's what we'd need to do:
1. Extend [download.js](https://github.com/gunar/shellcheck/blob/master/download.js#L4) to point to the [windows zip release](https://github.com/koalaman/shellcheck/releases) (slightly different URL)
2. Unzip the binary (while avoiding the [possible problem with dependencies](https://github.com/gunar/shellcheck/issues/16#issuecomment-520835526), which [might not be a problem afterall](https://github.com/gunar/shellcheck/issues/16#issuecomment-554368899))
3. Test on a Windows machine (I don't have one at the moment)

**Comment by joelvaneenwyk** [comment]
@gunar , I took this a bit further than originally planned and made this into a proper module/wrapper for NodeJS so that you can do:

`const shellcheck = require("node-shellcheck");
shellcheck("tests/example.bash");`

Check out the draft branch here:

* [joelvaneenwyk/shellcheck at windows-support](https://github.com/joelvaneenwyk/shellcheck/tree/windows-support)

@gunar , before I open a pull request on this one can you please do a quick review to align on direction? I don't want to spend too much time cleaning/squashing until it makes sense. You can also see successful run on CI here: [Add doc to return code. · joelvaneenwyk/shellcheck@eae5c97](https://github.com/joelvaneenwyk/shellcheck/runs/972747678?check_suite_focus=true)

**Comment by gunar** [comment]
Overall looks good to me! Good work.

There's a couple of things I'd mention:
1. We're using the package `shelljs` in a single place (to call shellcheck). We could drop this dependency in favor of the native `child_process` library.
2. It seems to me that, as is, `shellcheck()` is synchronous (i.e. thread-blocking). I believe a Promise API should be the default for us, with the sync as a method (e.g. `shellcheck.sync()`). 
3. I wonder if `shellcheck()` should return not just the exit code, but the contents of the error message as well (i.e. stdout/stderr).

Would love to hear more about your use-case for being able to call shellcheck directly from NodeJS. Having your thoughts here would also work as documentation of our thought process, should we revisit this feature in the future.

Looking forward to continuing our conversation.

**Comment by kidroca** [comment]
On a win env - `npm install` fails to complete for a project containing `shellcheck` as dependency  _(due to `./install.sh`)_

Is there anything we can do to at least allow `npm install` to complete even if we can't use `shellcheck` for linting (on win)?

**Comment by carlocorradini** [comment]
Windows can run POSIX shell scripts thanks to git bash. However, I think it's far way easier to convert `install.sh` to a simple node script (`install.js`) and use [node tar](https://www.npmjs.com/package/tar) to unzip.
Note that you can run the script on Windows by running (manually) install.sh, unfortunately calling from a npm script does not work :/

**Comment by carlocorradini** [comment]
Please, see PR #34

**Comment by gunar** [comment]
This will soon be released in #34.
